# Generated by Django 6.0.5 on 2026-05-28 00:34

from django.db import migrations


def seed_grade_prices(apps, schema_editor):
    GradePrice = apps.get_model('grading', 'GradePrice')
    defaults = [
        {'grade_letter': 'A', 'price_per_unit': 50.00},
        {'grade_letter': 'B', 'price_per_unit': 45.00},
        {'grade_letter': 'C', 'price_per_unit': 38.00},
    ]
    for entry in defaults:
        GradePrice.objects.get_or_create(
            grade_letter=entry['grade_letter'],
            effective_from='2026-01-01',
            defaults={'price_per_unit': entry['price_per_unit']},
        )


def reverse_seed(apps, schema_editor):
    GradePrice = apps.get_model('grading', 'GradePrice')
    GradePrice.objects.filter(effective_from='2026-01-01').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_grade_prices, reverse_seed),
    ]
