# Generated by Django 6.0.5 on 2026-05-28 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_seed_grade_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_letter',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('PREMIUM', 'Premium'), ('STANDARD', 'Standard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
