# Generated by Django 6.0.5 on 2026-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_add_grade_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_inventory_updated',
            field=models.BooleanField(default=False),
        ),
    ]
