# Generated by Django 6.0.5 on 2026-06-16 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_cooperative_prefix'),
        ('deliveries', '0005_alter_delivery_grade_alter_delivery_shift_and_more'),
        ('grading', '0007_grade_deleted_at_grade_deleted_via_cascade_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['cooperative', 'created_at'], name='idx_grade_coop_created'),
        ),
    ]
