# Generated by Django 6.0.5 on 2026-07-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_grade_idx_grade_coop_created'),
        ('payment_engine', '0008_farmerpayment_idx_pay_coop_cycle_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='payment_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='payment_engine.paymentcycle'),
        ),
    ]
