# Generated by Django 6.0.5 on 2026-05-28 08:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0005_alter_cooperative_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(db_index=True, max_length=30)),
                ('product_type', models.CharField(max_length=20)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('quantity_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'ordering': ['-created_at'],
            },
        ),
    ]
