# Generated by Django 6.0.5 on 2026-07-03 20:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0013_remove_cooperative_coffee_levy_per_kg_and_more'),
        ('inventory', '0003_inventory_deleted_at_and_more'),
        ('payment_engine', '0008_farmerpayment_idx_pay_coop_cycle_farmer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_via_cascade_from', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(db_index=True, max_length=20)),
                ('grade', models.CharField(db_index=True, max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory (cycle pool)', 'verbose_name_plural': 'Inventory (cycle pools)'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='payment_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_pools', to='payment_engine.paymentcycle'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('cooperative', 'payment_cycle', 'product_type', 'grade'), name='unique_inventory_cycle_pool'),
        ),
        migrations.AddField(
            model_name='stock',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('cooperative', 'product_type', 'grade'), name='unique_stock_coop_product_grade'),
        ),
    ]
