# Generated by Django 6.0.5 on 2026-05-30 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0006_cooperative_minimum_payout_amount'),
        ('farmers', '0006_farmer_has_active_loan'),
        ('payment_engine', '0004_farmerpayment_hold_reason_farmerpayment_is_on_hold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('command_id', models.CharField(choices=[('BusinessPayment', 'Business Payment'), ('SalaryPayment', 'Salary Payment'), ('PromotionPayment', 'Promotion Payment')], default='SalaryPayment', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_disbursements', to=settings.AUTH_USER_MODEL)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disbursements', to=settings.AUTH_USER_MODEL)),
                ('payment_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_batches', to='payment_engine.paymentcycle')),
            ],
            options={
                'verbose_name': 'Disbursement Batch',
                'verbose_name_plural': 'Disbursement Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisbursementTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('M_PESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], max_length=10)),
                ('recipient_identifier', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100)),
                ('result_code', models.CharField(blank=True, max_length=20)),
                ('result_desc', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('withholding_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='disbursement.disbursementbatch')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_transactions', to='farmers.farmer')),
                ('farmer_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_transactions', to='payment_engine.farmerpayment')),
            ],
            options={
                'verbose_name': 'Disbursement Transaction',
                'verbose_name_plural': 'Disbursement Transactions',
                'ordering': ['-created_at'],
                'unique_together': {('conversation_id', 'transaction_id')},
            },
        ),
    ]
