# Generated by Django 6.0.5 on 2026-05-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementbatch',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='disbursementbatch',
            name='originator_conversation_id',
        ),
    ]
