# Generated by Django 6.0.5 on 2026-06-16 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_cooperative_prefix'),
        ('disbursement', '0003_disbursementbatch_deleted_at_and_more'),
        ('farmers', '0012_add_soft_delete_to_membership'),
        ('payment_engine', '0007_farmerpayment_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='disbursementbatch',
            index=models.Index(fields=['cooperative', 'created_at', 'status'], name='idx_dsb_coop_date_status'),
        ),
        migrations.AddIndex(
            model_name='disbursementtransaction',
            index=models.Index(fields=['cooperative', 'batch', 'status'], name='idx_dsb_txn_coop_batch_st'),
        ),
    ]
