# Generated by Django 6.0.5 on 2026-06-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement', '0004_disbursementbatch_idx_dsb_coop_date_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursementbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
