# Generated by Django 6.0.5 on 2026-07-13 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0013_remove_cooperative_coffee_levy_per_kg_and_more'),
        ('disbursement', '0005_alter_disbursementbatch_status'),
        ('farmers', '0013_alter_farmer_date_joined_alter_farmer_is_active_and_more'),
        ('payment_engine', '0008_farmerpayment_idx_pay_coop_cycle_farmer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='disbursementtransaction',
            index=models.Index(fields=['status', 'sent_at'], name='idx_dsb_txn_status_sent_at'),
        ),
        migrations.AddIndex(
            model_name='disbursementtransaction',
            index=models.Index(fields=['batch', 'status', 'payment_method'], name='idx_dsb_txn_batch_st_method'),
        ),
    ]
