# Generated by Django 6.0.5 on 2026-07-14 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0013_remove_cooperative_coffee_levy_per_kg_and_more'),
        ('disbursement', '0006_add_performance_indexes'),
        ('farmers', '0013_alter_farmer_date_joined_alter_farmer_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursementbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('FAILED', 'Failed'), ('REVIEW', 'Review'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='FailedDisbursement',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_via_cascade_from', models.UUIDField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_identifier', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('failure_reason', models.TextField()),
                ('conversation_id', models.CharField(blank=True, max_length=100)),
                ('transaction_id_mpesa', models.CharField(blank=True, max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_disbursements', to='disbursement.disbursementbatch')),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.farmer')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_failed_disbursements', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letter_entries', to='disbursement.disbursementtransaction')),
            ],
            options={
                'verbose_name': 'Failed Disbursement',
                'verbose_name_plural': 'Failed Disbursements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved', 'created_at'], name='idx_fdb_resolved_date')],
            },
        ),
    ]
