# Generated by Django 6.0.5 on 2026-05-29 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0005_alter_cooperative_prefix'),
        ('farmers', '0005_farmer_latitude_farmer_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPUTING', 'Computing'), ('COMPUTED', 'Computed'), ('LOCKED', 'Locked')], db_index=True, default='DRAFT', max_length=20)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_payment_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Cycle',
                'verbose_name_plural': 'Payment Cycles',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='FarmerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grade_breakdown', models.JSONField(blank=True, default=dict)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.JSONField(blank=True, default=dict)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computation_log', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='farmers.farmer')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_payments', to='payment_engine.paymentcycle')),
            ],
            options={
                'verbose_name': 'Farmer Payment',
                'verbose_name_plural': 'Farmer Payments',
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'farmer')},
            },
        ),
    ]
