# Generated by Django 6.0.5 on 2026-05-29 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerpayment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentcycle',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentcycle',
            name='has_warnings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentcycle',
            name='total_cooperative_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentcycle',
            name='total_levy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentcycle',
            name='total_loan_repayments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ComputationWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error')], default='WARNING', max_length=20)),
                ('message', models.TextField()),
                ('delivery_id', models.UUIDField(blank=True, null=True)),
                ('farmer_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='payment_engine.paymentcycle')),
            ],
            options={
                'verbose_name': 'Computation Warning',
                'verbose_name_plural': 'Computation Warnings',
                'ordering': ['-created_at'],
            },
        ),
    ]
