# Generated by Django 6.0.5 on 2026-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_engine', '0002_farmerpayment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcycle',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
