# Generated by Django 6.0.5 on 2026-05-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_engine', '0003_alter_paymentcycle_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerpayment',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='is_subject_to_withholding_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentcycle',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPUTING', 'Computing'), ('COMPUTED', 'Computed'), ('LOCKED', 'Locked'), ('DISBURSED', 'Disbursed')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
