# Generated by Django 6.0.5 on 2026-05-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_engine', '0004_farmerpayment_hold_reason_farmerpayment_is_on_hold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerpayment',
            name='carried_forward_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='carry_forward_reason',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
