# Generated by Django 6.0.5 on 2026-06-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_engine', '0005_add_carry_forward_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcycle',
            name='total_input_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
