# Generated by Django 6.0.5 on 2026-06-16 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_cooperative_prefix'),
        ('farmers', '0013_alter_farmer_date_joined_alter_farmer_is_active_and_more'),
        ('payment_engine', '0007_farmerpayment_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farmerpayment',
            index=models.Index(fields=['cooperative', 'cycle', 'farmer'], name='idx_pay_coop_cycle_farmer'),
        ),
        migrations.AddIndex(
            model_name='farmerpayment',
            index=models.Index(fields=['cooperative', 'farmer', 'cycle'], name='idx_pay_coop_farmer_cycle'),
        ),
        migrations.AddIndex(
            model_name='paymentcycle',
            index=models.Index(fields=['cooperative', 'start_date', 'end_date'], name='idx_paymentcycle_coop_dates'),
        ),
    ]
