# Generated by Django 6.0.5 on 2026-07-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0013_remove_cooperative_coffee_levy_per_kg_and_more'),
        ('farmers', '0013_alter_farmer_date_joined_alter_farmer_is_active_and_more'),
        ('payment_engine', '0008_farmerpayment_idx_pay_coop_cycle_farmer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farmerpayment',
            index=models.Index(fields=['farmer', 'payment_status', 'carry_forward_reason'], name='idx_fp_farmer_status_carryfwd'),
        ),
    ]
