# Generated by Django 6.0.5 on 2026-07-14 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0013_remove_cooperative_coffee_levy_per_kg_and_more'),
        ('payment_engine', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='computationwarning',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computation_warnings', to='cooperatives.cooperative'),
        ),
        migrations.AlterField(
            model_name='computationwarning',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='payment_engine.paymentcycle'),
        ),
    ]
