# Generated by Django 6.0.5 on 2026-05-31 02:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0006_cooperative_minimum_payout_amount'),
        ('farmers', '0006_farmer_has_active_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('USSD', 'USSD'), ('EMAIL', 'Email'), ('IN_APP', 'In App')], max_length=10)),
                ('notification_type', models.CharField(choices=[('DELIVERY_CONFIRMATION', 'Delivery Confirmation'), ('PAYMENT_SENT', 'Payment Sent'), ('PAYMENT_FAILED', 'Payment Failed'), ('GRADE_RESULT', 'Grade Result'), ('LOAN_APPROVAL', 'Loan Approval'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('USSD_SESSION', 'USSD Session'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cooperatives.cooperative')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('current_menu', models.CharField(default='HOME', max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_sessions', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'USSD Session',
                'verbose_name_plural': 'USSD Sessions',
                'ordering': ['-last_activity'],
            },
        ),
    ]
