# Generated by Django 6.0.5 on 2026-06-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DELIVERY_CONFIRMATION', 'Delivery Confirmation'), ('PAYMENT_SENT', 'Payment Sent'), ('PAYMENT_FAILED', 'Payment Failed'), ('GRADE_RESULT', 'Grade Result'), ('LOAN_APPROVAL', 'Loan Approval'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_DEFAULTED', 'Loan Defaulted'), ('USSD_SESSION', 'USSD Session'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
    ]
