# Generated by Django 6.0.5 on 2026-06-06 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0010_drop_old_farmer_fields'),
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdsession',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_sessions', to='farmers.farmercooperativemembership'),
        ),
    ]
