# Generated by Django 6.0.5 on 2026-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_cooperative_prefix'),
        ('farmers', '0013_alter_farmer_date_joined_alter_farmer_is_active_and_more'),
        ('notifications', '0004_notification_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['cooperative', 'status', 'channel'], name='idx_notif_coop_status_chan'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('status', 'PENDING')), fields=['cooperative', 'channel'], name='idx_notification_unsent'),
        ),
    ]
