# Generated by Django 6.0.5 on 2026-07-16 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0015_add_ussd_menu_config'),
        ('notifications', '0005_notification_idx_notif_coop_status_chan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDMenuConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_key', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('options', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_menus', to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name': 'USSD Menu Config',
                'verbose_name_plural': 'USSD Menu Configs',
                'ordering': ['cooperative', 'order'],
                'unique_together': {('cooperative', 'menu_key', 'language')},
            },
        ),
    ]
