# Generated by Django 6.0.5 on 2026-05-28 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('cooperatives', '0005_alter_cooperative_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cooperatives.cooperative'),
        ),
    ]
