# Generated by Django 6.0.5 on 2026-05-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_auditlog_cooperative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('OVERRIDE', 'Override'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('RUN', 'Run')], max_length=20),
        ),
    ]
