# Generated by Django 6.0.5 on 2026-06-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auditlog_ip_address_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('OVERRIDE', 'Override'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('RUN', 'Run'), ('LOGIN', 'Login'), ('DISBURSE', 'Disburse'), ('GRADE', 'Grade'), ('PDF_GENERATED', 'PDF Generated'), ('NOTIFY', 'Notify')], max_length=20),
        ),
    ]
