# Generated by Django 6.0.5 on 2026-06-02 04:15

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_auditlog_action'),
        ('cooperatives', '0007_add_revenue_share_and_prorate_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='base_auditl_created_11a65a_brin'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['cooperative', 'resource_type', 'resource_id', 'created_at'], name='base_auditl_coopera_810bb8_idx'),
        ),
    ]
