# Generated by Django 6.0.5 on 2026-06-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_enable_pg_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('OVERRIDE', 'Override'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('RUN', 'Run'), ('LOGIN', 'Login'), ('DISBURSE', 'Disburse'), ('GRADE', 'Grade'), ('PDF_GENERATED', 'PDF Generated'), ('NOTIFY', 'Notify'), ('MEMBERSHIP_ADDED', 'Membership Added'), ('MEMBERSHIP_UPDATED', 'Membership Updated'), ('MEMBERSHIP_DEACTIVATED', 'Membership Deactivated'), ('MEMBERSHIP_REACTIVATED', 'Membership Reactivated')], max_length=50),
        ),
    ]
