# Generated by Django 6.0.5 on 2026-06-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_increase_audit_action_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('OVERRIDE', 'Override'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('RUN', 'Run'), ('LOGIN', 'Login'), ('DISBURSE', 'Disburse'), ('GRADE', 'Grade'), ('PDF_GENERATED', 'PDF Generated'), ('NOTIFY', 'Notify'), ('MEMBERSHIP_ADDED', 'Membership Added'), ('MEMBERSHIP_UPDATED', 'Membership Updated'), ('MEMBERSHIP_DEACTIVATED', 'Membership Deactivated'), ('MEMBERSHIP_REACTIVATED', 'Membership Reactivated'), ('ADMIN_CREATE', 'Admin Create'), ('ADMIN_UPDATE', 'Admin Update'), ('ADMIN_DELETE', 'Admin Delete'), ('ADMIN_ACTION', 'Admin Action'), ('IMPERSONATE', 'Impersonate'), ('FORCE_STATUS', 'Force Status'), ('TRANSFER_COOPERATIVE', 'Transfer Cooperative')], max_length=50),
        ),
    ]
