# Generated by Django 6.0.5 on 2026-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='deleted_via_cascade_from',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('OVERRIDE', 'Override'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('RUN', 'Run'), ('LOGIN', 'Login'), ('DISBURSE', 'Disburse'), ('GRADE', 'Grade'), ('PDF_GENERATED', 'PDF Generated'), ('NOTIFY', 'Notify'), ('MEMBERSHIP_ADDED', 'Membership Added'), ('MEMBERSHIP_UPDATED', 'Membership Updated'), ('MEMBERSHIP_DEACTIVATED', 'Membership Deactivated'), ('MEMBERSHIP_REACTIVATED', 'Membership Reactivated'), ('ADMIN_CREATE', 'Admin Create'), ('ADMIN_UPDATE', 'Admin Update'), ('ADMIN_DELETE', 'Admin Delete'), ('ADMIN_ACTION', 'Admin Action'), ('IMPERSONATE', 'Impersonate'), ('FORCE_STATUS', 'Force Status'), ('TRANSFER_COOPERATIVE', 'Transfer Cooperative'), ('ADMIN_PURGE', 'Admin Purge')], max_length=50),
        ),
    ]
