# Generated by Django 6.0.5 on 2026-06-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
