# Generated by Django 6.0.5 on 2026-07-13 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_make_auditlog_resource_id_nullable'),
        ('cooperatives', '0013_remove_cooperative_coffee_levy_per_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('OVERRIDE', 'Override'), ('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('RUN', 'Run'), ('LOGIN', 'Login'), ('DISBURSE', 'Disburse'), ('GRADE', 'Grade'), ('PDF_GENERATED', 'PDF Generated'), ('NOTIFY', 'Notify'), ('MEMBERSHIP_ADDED', 'Membership Added'), ('MEMBERSHIP_UPDATED', 'Membership Updated'), ('MEMBERSHIP_DEACTIVATED', 'Membership Deactivated'), ('MEMBERSHIP_REACTIVATED', 'Membership Reactivated'), ('ADMIN_CREATE', 'Admin Create'), ('ADMIN_UPDATE', 'Admin Update'), ('ADMIN_DELETE', 'Admin Delete'), ('ADMIN_ACTION', 'Admin Action'), ('IMPERSONATE', 'Impersonate'), ('FORCE_STATUS', 'Force Status'), ('TRANSFER_COOPERATIVE', 'Transfer Cooperative'), ('ADMIN_PURGE', 'Admin Purge'), ('SNAPSHOT_FAILED', 'Snapshot Failed'), ('EXPORT_FAILED', 'Export Failed'), ('PUBLISH', 'Published legal document'), ('ACCEPT', 'Accepted legal document'), ('DEACTIVATE', 'Deactivated legal document')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['cooperative', 'action', 'created_at'], name='idx_auditlog_coop_action_date'),
        ),
    ]
