# Generated by Django 6.0.5 on 2026-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='twofactorotp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('PASSWORD_RESET', 'Password Reset'), ('ACTION_CONFIRM', 'Action Confirm'), ('FARMER_LOGIN', 'Farmer Login')], max_length=20),
        ),
    ]
