# Generated by Django 6.0.5 on 2026-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_user_deleted_at_user_restored_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_via_cascade_from',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
