# Generated by Django 6.0.5 on 2026-06-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_backupcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupCode',
        ),
    ]
