# Generated by Django 6.0.5 on 2026-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_remove_backupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
