# Generated by Django 6.0.5 on 2026-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_user_invite_revoked'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='twofactorotp',
            index=models.Index(fields=['user', 'purpose', 'is_used', 'expires_at'], name='idx_otp_usr_purp_used_exp'),
        ),
    ]
