# Generated by Django 6.0.5 on 2026-06-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_twofactorotp_idx_otp_usr_purp_used_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('grader', 'Grader'), ('farmer', 'Farmer'), ('auditor', 'Internal Auditor'), ('external_auditor', 'External Auditor')], max_length=20, null=True),
        ),
    ]
