# Generated by Django 6.0.5 on 2026-07-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0011_user_google_sub'),
        ('cooperatives', '0013_remove_cooperative_coffee_levy_per_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('grader', 'Grader'), ('farmer', 'Farmer'), ('auditor', 'Internal Auditor'), ('external_auditor', 'External Auditor')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cooperative', 'role'], name='idx_user_coop_role'),
        ),
    ]
