# Generated by Django 6.0.5 on 2026-05-27 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0003_cooperative_last_delivery_date_and_more'),
        ('farmers', '0002_farmer_email_alter_farmer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('MILK', 'Milk'), ('COFFEE_CHERRIES', 'Coffee Cherries'), ('HONEY', 'Honey'), ('OTHER', 'Other')], max_length=20)),
                ('batch_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GRADED', 'Graded'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('quality_metrics', models.JSONField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('date_delivered', models.DateTimeField(auto_now_add=True)),
                ('shift', models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Evening')], max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('local_id', models.CharField(blank=True, max_length=100)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='farmers.farmer')),
                ('grader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-date_delivered'],
            },
        ),
    ]
