# Generated by Django 6.0.5 on 2026-05-27 14:51

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_cooperative_last_delivery_date_and_more'),
        ('deliveries', '0001_initial'),
        ('farmers', '0002_farmer_email_alter_farmer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='batch_id',
            field=models.CharField(db_index=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date_delivered',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='product_type',
            field=models.CharField(choices=[('MILK', 'Milk'), ('COFFEE_CHERRIES', 'Coffee Cherries'), ('HONEY', 'Honey'), ('OTHER', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GRADED', 'Graded'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='volume_litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(condition=models.Q(('local_id__gt', '')), fields=('cooperative', 'local_id'), name='unique_delivery_local_id'),
        ),
    ]
