# Generated by Django 6.0.5 on 2026-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_delivery_batch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
