# Generated by Django 6.0.5 on 2026-06-16 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_cooperative_prefix'),
        ('deliveries', '0004_delivery_deleted_at_and_more'),
        ('farmers', '0012_add_soft_delete_to_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='grade',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='shift',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Evening')], db_index=True, max_length=2),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['cooperative', 'date_delivered', 'status'], name='idx_delivery_coop_date_status'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['cooperative', 'date_delivered', 'grade'], name='idx_delivery_coop_date_grade'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['cooperative', 'date_delivered', 'product_type'], name='idx_del_coop_date_prodtype'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['cooperative', 'date_delivered', 'shift'], name='idx_delivery_coop_date_shift'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(condition=models.Q(('status', 'PENDING')), fields=['cooperative', '-date_delivered'], name='idx_del_pending_grader'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['cooperative'], name='idx_delivery_live_records'),
        ),
    ]
