# Generated by Django 6.0.5 on 2026-07-07 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0013_remove_cooperative_coffee_levy_per_kg_and_more'),
        ('deliveries', '0005_alter_delivery_grade_alter_delivery_shift_and_more'),
        ('farmers', '0013_alter_farmer_date_joined_alter_farmer_is_active_and_more'),
        ('routes', '0003_collectionroute_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='route_stop',
            field=models.ForeignKey(blank=True, db_default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='routes.routestop'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['cooperative', 'route_stop', 'date_delivered'], name='idx_del_coop_stop_date'),
        ),
    ]
