# Generated by Django 6.0.5 on 2026-07-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_delivery_route_stop_delivery_idx_del_coop_stop_date'),
        ('routes', '0003_collectionroute_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='route_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='routes.routestop'),
        ),
    ]
