from django.urls import path

from apps.admin.views import (
    AdminAnalyticsViewSet,
    AdminAuditLogView,
    AdminBinSummaryView,
    AdminCeleryTasksView,
    AdminCooperativeActivateView,
    AdminCooperativeBinView,
    AdminCooperativeBulkActionView,
    AdminCooperativeDeactivateView,
    AdminCooperativeDeleteView,
    AdminCooperativePurgeView,
    AdminCooperativeRestoreView,
    AdminCooperativeViewSet,
    AdminDashboardView,
    AdminDeliveryAssignGradeView,
    AdminDeliveryBinView,
    AdminDeliveryForceStatusView,
    AdminDeliveryPurgeView,
    AdminDeliveryRestoreView,
    AdminDeliveryViewSet,
    AdminDisbursementBatchApproveView,
    AdminDisbursementBatchRejectView,
    AdminDisbursementBatchViewSet,
    AdminFarmerBinView,
    AdminFarmerBulkActionView,
    AdminFarmerPaymentHoldView,
    AdminFarmerPaymentViewSet,
    AdminFarmerRestoreView,
    AdminFarmerViewSet,
    AdminHealthView,
    AdminInviteDetailView,
    AdminInviteListView,
    AdminInviteResendView,
    AdminInviteRevokeView,
    AdminInviteView,
    AdminLoanApproveView,
    AdminLoanBinView,
    AdminLoanMarkCompletedView,
    AdminLoanMarkDefaultedView,
    AdminLoanPurgeView,
    AdminLoanRejectView,
    AdminLoanRestoreView,
    AdminLoanViewSet,
    AdminMigrationHealthView,
    AdminOTPTokenInvalidateAllView,
    AdminOTPTokenView,
    AdminPaymentCycleBinView,
    AdminPaymentCycleLockView,
    AdminPaymentCyclePurgeView,
    AdminPaymentCycleRestoreView,
    AdminPaymentCycleUnlockView,
    AdminPaymentCycleViewSet,
    AdminUserActivateView,
    AdminUserBinView,
    AdminUserBulkActionView,
    AdminUserDeactivateView,
    AdminUserDeleteView,
    AdminUserForceLogoutView,
    AdminUserPurgeView,
    AdminUserResetPasswordView,
    AdminUserRestoreView,
    AdminUserToggle2FAView,
    AdminUserViewSet,
    CreateSuperUserView,
    ImpersonateView,
    RevokeAllSessionsView,
)

urlpatterns = [
    path('bin/', AdminBinSummaryView.as_view()),
    path('bin/users/', AdminUserBinView.as_view()),
    path('bin/cooperatives/', AdminCooperativeBinView.as_view()),
    path('bin/users/<uuid:pk>/purge/', AdminUserPurgeView.as_view()),
    path('bin/cooperatives/<uuid:pk>/purge/', AdminCooperativePurgeView.as_view()),
    path('bin/farmers/', AdminFarmerBinView.as_view()),
    path('bin/deliveries/', AdminDeliveryBinView.as_view()),
    path('bin/deliveries/<uuid:pk>/purge/', AdminDeliveryPurgeView.as_view()),
    path('bin/loans/', AdminLoanBinView.as_view()),
    path('bin/loans/<uuid:pk>/purge/', AdminLoanPurgeView.as_view()),
    path('bin/payment-cycles/', AdminPaymentCycleBinView.as_view()),
    path('bin/payment-cycles/<uuid:pk>/purge/', AdminPaymentCyclePurgeView.as_view()),
    path('users/bulk-action/', AdminUserBulkActionView.as_view()),
    path('users/create-superuser/', CreateSuperUserView.as_view()),
    path('users/', AdminUserViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('users/<uuid:pk>/', AdminUserViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('users/<uuid:pk>/activate/', AdminUserActivateView.as_view()),
    path('users/<uuid:pk>/deactivate/', AdminUserDeactivateView.as_view()),
    path('users/<uuid:pk>/reset-password/', AdminUserResetPasswordView.as_view()),
    path('users/<uuid:pk>/toggle-2fa/', AdminUserToggle2FAView.as_view()),
    path('users/<uuid:pk>/delete/', AdminUserDeleteView.as_view()),
    path('users/<uuid:pk>/restore/', AdminUserRestoreView.as_view()),
    path('users/<uuid:pk>/force-logout/', AdminUserForceLogoutView.as_view()),
    path('impersonate/<uuid:user_id>/', ImpersonateView.as_view()),
    path('cooperatives/bulk-action/', AdminCooperativeBulkActionView.as_view()),
    path('cooperatives/', AdminCooperativeViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('cooperatives/<uuid:pk>/', AdminCooperativeViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('cooperatives/<uuid:pk>/activate/', AdminCooperativeActivateView.as_view()),
    path('cooperatives/<uuid:pk>/delete/', AdminCooperativeDeleteView.as_view()),
    path('cooperatives/<uuid:pk>/restore/', AdminCooperativeRestoreView.as_view()),
    path('cooperatives/<uuid:pk>/deactivate/', AdminCooperativeDeactivateView.as_view()),
    path('farmers/<uuid:pk>/restore/', AdminFarmerRestoreView.as_view()),
    path('farmers/bulk-action/', AdminFarmerBulkActionView.as_view()),
    path('deliveries/<uuid:pk>/restore/', AdminDeliveryRestoreView.as_view()),
    path('loans/<uuid:pk>/restore/', AdminLoanRestoreView.as_view()),
    path('payment-cycles/<uuid:pk>/restore/', AdminPaymentCycleRestoreView.as_view()),
    path('farmers/', AdminFarmerViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('farmers/<uuid:pk>/', AdminFarmerViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'})),
    path('deliveries/', AdminDeliveryViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('deliveries/<uuid:pk>/', AdminDeliveryViewSet.as_view({'get': 'retrieve'})),
    path('deliveries/<uuid:pk>/force-status/', AdminDeliveryForceStatusView.as_view()),
    path('deliveries/<uuid:pk>/assign-grade/', AdminDeliveryAssignGradeView.as_view()),
    path('payment-cycles/', AdminPaymentCycleViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('payment-cycles/<uuid:pk>/', AdminPaymentCycleViewSet.as_view({'get': 'retrieve'})),
    path('payment-cycles/<uuid:pk>/lock/', AdminPaymentCycleLockView.as_view()),
    path('payment-cycles/<uuid:pk>/unlock/', AdminPaymentCycleUnlockView.as_view()),
    path('disbursement-batches/', AdminDisbursementBatchViewSet.as_view({'get': 'list'})),
    path('disbursement-batches/<uuid:pk>/', AdminDisbursementBatchViewSet.as_view({'get': 'retrieve'})),
    path('disbursement-batches/<uuid:pk>/approve/', AdminDisbursementBatchApproveView.as_view()),
    path('disbursement-batches/<uuid:pk>/reject/', AdminDisbursementBatchRejectView.as_view()),
    path('farmer-payments/', AdminFarmerPaymentViewSet.as_view({'get': 'list'})),
    path('farmer-payments/<uuid:pk>/', AdminFarmerPaymentViewSet.as_view({'get': 'retrieve'})),
    path('farmer-payments/<uuid:pk>/hold/', AdminFarmerPaymentHoldView.as_view()),
    path('loans/', AdminLoanViewSet.as_view({'get': 'list'})),
    path('loans/<uuid:pk>/', AdminLoanViewSet.as_view({'get': 'retrieve'})),
    path('loans/<uuid:pk>/approve/', AdminLoanApproveView.as_view()),
    path('loans/<uuid:pk>/reject/', AdminLoanRejectView.as_view()),
    path('loans/<uuid:pk>/mark-defaulted/', AdminLoanMarkDefaultedView.as_view()),
    path('loans/<uuid:pk>/mark-completed/', AdminLoanMarkCompletedView.as_view()),
    path('otp-tokens/', AdminOTPTokenView.as_view()),
    path('otp-tokens/<uuid:user_id>/invalidate-all/', AdminOTPTokenInvalidateAllView.as_view()),
    path('dashboard/', AdminDashboardView.as_view()),
    path('audit-logs/', AdminAuditLogView.as_view()),
    path('health/', AdminHealthView.as_view()),
    path('migration-health/', AdminMigrationHealthView.as_view()),
    path('celery/tasks/', AdminCeleryTasksView.as_view()),
    path('auth/invites/', AdminInviteListView.as_view()),
    path('auth/invites/<uuid:pk>/', AdminInviteDetailView.as_view()),
    path('auth/invite/', AdminInviteView.as_view()),
    path('auth/invite/<uuid:pk>/revoke/', AdminInviteRevokeView.as_view()),
    path('auth/invite/<uuid:pk>/resend/', AdminInviteResendView.as_view()),
    path('auth/revoke-all-sessions/', RevokeAllSessionsView.as_view()),
    path('analytics/dashboard/', AdminAnalyticsViewSet.as_view({'get': 'dashboard'}), name='admin-analytics-dashboard'),
    path('analytics/production/', AdminAnalyticsViewSet.as_view({'get': 'production'}), name='admin-analytics-production'),
    path('analytics/financial/', AdminAnalyticsViewSet.as_view({'get': 'financial'}), name='admin-analytics-financial'),
    path('analytics/farmers/', AdminAnalyticsViewSet.as_view({'get': 'farmers'}), name='admin-analytics-farmers'),
    path('analytics/sales/', AdminAnalyticsViewSet.as_view({'get': 'sales'}), name='admin-analytics-sales'),
    path('analytics/loans/', AdminAnalyticsViewSet.as_view({'get': 'loans'}), name='admin-analytics-loans'),
    path('analytics/operations/', AdminAnalyticsViewSet.as_view({'get': 'operations'}), name='admin-analytics-operations'),
    path('analytics/disbursements/', AdminAnalyticsViewSet.as_view({'get': 'disbursements'}), name='admin-analytics-disbursements'),
    path('analytics/seasonal/', AdminAnalyticsViewSet.as_view({'get': 'seasonal'}), name='admin-analytics-seasonal'),
    path('analytics/payment-efficiency/', AdminAnalyticsViewSet.as_view({'get': 'payment_efficiency'}), name='admin-analytics-payment-efficiency'),
    path('analytics/farmer-retention/', AdminAnalyticsViewSet.as_view({'get': 'farmer_retention'}), name='admin-analytics-farmer-retention'),
    path('analytics/leaderboard/', AdminAnalyticsViewSet.as_view({'get': 'leaderboard'}), name='admin-analytics-leaderboard'),
]
