# Generated by Django 6.0.5 on 2026-05-29 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0005_alter_cooperative_prefix'),
        ('farmers', '0005_farmer_latitude_farmer_longitude'),
        ('payment_engine', '0002_farmerpayment_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deduction_type', models.CharField(choices=[('LEVY', 'Levy'), ('LOAN_REPAYMENT', 'Loan Repayment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payment_engine.paymentcycle')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
                'ordering': ['-created_at'],
            },
        ),
    ]
