# Generated by Django 6.0.5 on 2026-06-01 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0006_cooperative_minimum_payout_amount'),
        ('deductions', '0001_initial'),
        ('farmers', '0006_farmer_has_active_loan'),
        ('payment_engine', '0006_paymentcycle_total_input_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='deduction_type',
            field=models.CharField(choices=[('LEVY', 'Levy'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('INPUT_CREDIT', 'Input Credit')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='FarmInputCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplied_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative')),
                ('deducted_in_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_credits', to='payment_engine.paymentcycle')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_credits', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Farm Input Credit',
                'verbose_name_plural': 'Farm Input Credits',
                'ordering': ['-supplied_date'],
            },
        ),
    ]
