# Generated by Django 6.0.5 on 2026-06-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deductions', '0002_alter_deduction_deduction_type_farminputcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminputcredit',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount deducted per cycle. Defaults to amount (pay in full).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farminputcredit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='farminputcredit',
            name='total_deducted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
