# Generated by Django 6.0.5 on 2026-06-06 13:07

from django.db import migrations


def backfill_installment_fields(apps, schema_editor):
    FarmInputCredit = apps.get_model('deductions', 'FarmInputCredit')
    for credit in FarmInputCredit.objects.all():
        credit.installment_amount = credit.amount
        if credit.deducted_in_cycle_id is not None:
            credit.status = 'COMPLETED'
            credit.total_deducted = credit.amount
        else:
            credit.status = 'ACTIVE'
            credit.total_deducted = 0
        credit.save(update_fields=['installment_amount', 'status', 'total_deducted'])


class Migration(migrations.Migration):

    dependencies = [
        ('deductions', '0003_add_installment_fields'),
    ]

    operations = [
        migrations.RunPython(backfill_installment_fields, reverse_code=migrations.RunPython.noop),
    ]
