# Generated by Django 6.0.5 on 2026-06-16 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_cooperative_prefix'),
        ('deductions', '0005_deduction_deleted_at_and_more'),
        ('farmers', '0012_add_soft_delete_to_membership'),
        ('payment_engine', '0007_farmerpayment_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deduction',
            index=models.Index(fields=['cooperative', 'cycle', 'deduction_type'], name='idx_deduction_coop_cycle_type'),
        ),
        migrations.AddIndex(
            model_name='deduction',
            index=models.Index(fields=['cooperative', 'farmer', 'cycle'], name='idx_ded_coop_farmer_cycle'),
        ),
    ]
