# Generated by Django 6.0.5 on 2026-05-27 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('county', models.CharField(max_length=100)),
                ('produce_type', models.CharField(choices=[('DAIRY', 'Dairy'), ('COFFEE', 'Coffee'), ('HONEY', 'Honey')], max_length=20)),
                ('payment_model', models.CharField(choices=[('FIXED_PRICE', 'Fixed Price'), ('REVENUE_SHARE', 'Revenue Share')], max_length=20)),
                ('levy_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_shortcode', models.CharField(blank=True, max_length=20)),
                ('float_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(blank=True)),
                ('settlement_bank_name', models.CharField(blank=True, max_length=100)),
                ('settlement_bank_account', models.CharField(blank=True, max_length=30)),
                ('settlement_bank_branch', models.CharField(blank=True, max_length=100)),
                ('payment_day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parent_union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name': 'Cooperative',
                'verbose_name_plural': 'Cooperatives',
                'db_table': 'base_cooperative',
            },
        ),
    ]
