# Generated by Django 6.0.5 on 2026-05-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='till_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='year_established',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
