# Generated by Django 6.0.5 on 2026-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='last_member_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='prefix',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
