# Generated by Django 6.0.5 on 2026-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0002_cooperative_last_member_sequence_cooperative_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='last_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='last_delivery_sequence',
            field=models.IntegerField(default=0),
        ),
    ]
