# Generated by Django 6.0.5 on 2026-05-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_cooperative_last_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='inventory',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
