# Generated by Django 6.0.5 on 2026-05-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0004_cooperative_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
