# Generated by Django 6.0.5 on 2026-05-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0005_alter_cooperative_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='minimum_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
