# Generated by Django 6.0.5 on 2026-06-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0006_cooperative_minimum_payout_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='prorate_new_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='revenue_share_by_produce_type',
            field=models.BooleanField(default=False),
        ),
    ]
