# Generated by Django 6.0.5 on 2026-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0007_add_revenue_share_and_prorate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='logo',
            field=models.ImageField(blank=True, upload_to='cooperative_logos/'),
        ),
    ]
