# Generated by Django 6.0.5 on 2026-06-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0008_add_logo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
