# Generated by Django 6.0.5 on 2026-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0009_cooperative_deleted_at_cooperative_restored_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='deleted_via_cascade_from',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
