# Generated by Django 6.0.5 on 2026-06-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_cooperative_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='coffee_levy_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='honey_levy_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='milk_levy_per_litre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='transport_fee_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
