# Generated by Django 6.0.5 on 2026-06-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0012_cooperative_coffee_levy_per_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='coffee_levy_per_kg',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='honey_levy_per_kg',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='membership_fee',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='milk_levy_per_litre',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='transport_fee_per_km',
        ),
    ]
