# Generated by Django 6.0.5 on 2026-07-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0014_repair_cascade_orphans'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='ussd_delivery_limit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
