"""
Django settings for zaoapi project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG")

ALLOWED_HOSTS = ["*"]


# Application definition

AUTH_USER_MODEL = 'auth_api.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'apps.auth_api',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'cloudinary_storage',
    'cloudinary',
    'corsheaders',
    'django.contrib.postgres',

    # Local apps
    'zaoapi',
    'apps.base',
    'apps.cooperatives',
    'apps.users',
    'apps.farmers',
    'apps.deliveries',
    'apps.grading',
    'apps.inventory',
    'apps.routes',
    'apps.sales',
    'apps.payment_engine',
    'apps.deductions',
    'apps.loans',
    'apps.disbursement',
    'apps.notifications',
    'apps.statements',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.base.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

FIELD_ENCRYPTION_KEY = config("FIELD_ENCRYPTION_KEY")

ROOT_URLCONF = 'zaoapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zaoapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql',
		'NAME': config('DATABASE_NAME'),
		'USER': config('DATABASE_USER'),
		'PASSWORD': config('DATABASE_PASSWORD'),
		'HOST': config('DATABASE_HOST'),
		'PORT': config('DATABASE_PORT'),
	}
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

# M-Pesa Daraja API
MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY', default='')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET', default='')
MPESA_PASSKEY = config('MPESA_PASSKEY', default='')
MPESA_SHORTCODE = config('MPESA_SHORTCODE', default='')
MPESA_INITIATOR_NAME = config('MPESA_INITIATOR_NAME', default='testapi')
MPESA_INITIATOR_PASSWORD = config('MPESA_INITIATOR_PASSWORD', default='')
MPESA_PUBLIC_CERT_PATH = config('MPESA_PUBLIC_CERT_PATH', default=BASE_DIR / 'certs' / 'mpesa_public_cert.cer')
MPESA_ENVIRONMENT = config('MPESA_ENVIRONMENT', default='sandbox')
MPESA_B2C_RESULT_URL = config('MPESA_B2C_RESULT_URL', default='')
MPESA_B2C_TIMEOUT_URL = config('MPESA_B2C_TIMEOUT_URL', default='')
MPESA_DISBURSEMENT_BLACKOUT_START = config('MPESA_DISBURSEMENT_BLACKOUT_START', default='01:00')
MPESA_DISBURSEMENT_BLACKOUT_END = config('MPESA_DISBURSEMENT_BLACKOUT_END', default='04:00')
MPESA_CALLBACK_IP_WHITELIST = config('MPESA_CALLBACK_IP_WHITELIST', default='')

# Celery configuration
CELERY_BROKER_URL = config('REDIS_URL')
CELERY_RESULT_BACKEND = config('REDIS_URL')
CELERY_TIMEZONE = 'Africa/Nairobi'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'reconcile-stuck-disbursements': {
        'task': 'apps.disbursement.tasks.reconcile_stuck_transactions',
        'schedule': crontab(minute='*/15'),
    },
    'cleanup-expired-ussd-sessions': {
        'task': 'apps.notifications.tasks.cleanup_expired_ussd_sessions',
        'schedule': crontab(hour='2', minute='0'),
    },
    'cleanup-expired-otps': {
        'task': 'apps.auth_api.tasks.cleanup_expired_otps',
        'schedule': crontab(minute='*/30'),
    },
}

NOTIFICATIONS_DRY_RUN = config('NOTIFICATIONS_DRY_RUN', default=True, cast=bool)
AFRICASTALKING_USSD_CODE = config('AFRICASTALKING_USSD_CODE', default='*384*12345#')

# Email
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'request_otp': '5/hour',
        'verify_otp': '5/min',
        'farmer_request_otp': '3/hour',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Zao API',
    'DESCRIPTION': (
        'Zao is a comprehensive agricultural cooperative management platform '
        'that digitizes the entire farmer value chain, from collection '
        'and quality grading to payments, deductions, loans, and disbursements.\n\n'
        'The API enables cooperatives to manage farmers, track deliveries in '
        'real-time, compute payment cycles with automatic deductions, disburse '
        'payments via M-Pesa B2C (Daraja), bank transfers, or cash, and '
        'generate financial reports.\n\n'
        'All endpoints require JWT authentication unless noted otherwise. '
        'Include `Authorization: Bearer <token>` header.\n\n'
        '**Apps:**\n\n'
        '- **auth_api** — Authentication & JWT management: login, 2FA OTP (email), '
        'farmer OTP (SMS), token refresh, logout.\n'
        '- **cooperatives** — Cooperative entity CRUD with stats, enums, '
        'and current-cooperative lookup.\n'
        '- **users** — User account CRUD scoped to cooperative, self-profile endpoint.\n'
        '- **farmers** — Farmer profiles with full-text search, CSV import, '
        'nested cooperative membership (activate/deactivate).\n'
        '- **deliveries** — Milk delivery recording with offline sync, GPS map data, '
        'batch grouping, summary stats, SMS notifications.\n'
        '- **grading** — Milk quality grading with price tiers, manager overrides, '
        'image attachments, farmer disputes with resolution.\n'
        '- **inventory** — Read-only batch inventory with summary aggregation '
        'and low-stock threshold alerts.\n'
        '- **routes** — Collection route definitions with GPS stop assignment '
        'and farmer grouping.\n'
        '- **sales** — Buyer records and sales transactions with inventory '
        'availability checks.\n'
        '- **payment_engine** — Payment cycle lifecycle: draft, compute (Celery), '
        'preview, lock/unlock, hold/release payments, CSV export.\n'
        '- **deductions** — Loan repayment deductions and farm input credits, '
        'integrated with payment cycles.\n'
        '- **loans** — Loan lifecycle: create, approve, disburse, add/remove '
        'guarantors, mark completed or defaulted.\n'
        '- **disbursement** — Payment disbursement (M-Pesa B2C via Daraja, Bank, '
        'Cash): initiate, approve, send live, retry, export, confirm.\n'
        '- **notifications** — Notification log (SMS, email, in-app) and '
        "Africa's Talking USSD callback.\n"
        '- **statements** — Farmer payment PDF statements, payment history JSON, '
        'season/KRA/annual reports, audit log.'
    ),
    'VERSION': '1.0.0',
}

# CORS - TODO: restrict CORS_ALLOWED_ORIGINS in production
CORS_ALLOW_ALL_ORIGINS = True
