"""
Django settings for zaoapi project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import socket
from urllib.parse import urlparse
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1,.onrender.com,testserver,web").split(",")

TRASH_RETENTION_DAYS = config("TRASH_RETENTION_DAYS", default=30, cast=int)

# Propagate cloudinary credentials to os.environ for cloudinary_storage
_cloudinary_url = config("CLOUDINARY_URL", default="")
if _cloudinary_url:
    os.environ.setdefault("CLOUDINARY_URL", _cloudinary_url)

# Application definition

AUTH_USER_MODEL = 'auth_api.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'apps.auth_api',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'cloudinary_storage',
    'cloudinary',
    'corsheaders',
    'django_celery_beat',
    'django.contrib.postgres',

    # Local apps
    'zaoapi',
    'apps.base',
    'apps.cooperatives',
    'apps.users',
    'apps.farmers',
    'apps.deliveries',
    'apps.grading',
    'apps.inventory',
    'apps.routes',
    'apps.sales',
    'apps.payment_engine',
    'apps.deductions',
    'apps.loans',
    'apps.disbursement',
    'apps.notifications',
    'apps.statements',
    'apps.chat',
    'apps.admin',
    'apps.legal',
    'apps.analytics',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'apps.base.middleware.CorrelationIDMiddleware',
    'apps.base.middleware.RequestLoggingMiddleware',
    'apps.base.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.base.middleware.TenantMiddleware',
    'apps.base.middleware.LegalAcceptanceMiddleware',
    'apps.base.middleware.ForcePasswordChangeMiddleware',
    'apps.admin.middleware.SuperAdminIPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

FIELD_ENCRYPTION_KEY = config("FIELD_ENCRYPTION_KEY")

# OpenRouteService proxy
ORS_API_KEY = config("ORS_API_KEY", default="")
ORS_BASE_URL = config("ORS_BASE_URL", default="https://api.openrouteservice.org")
ORS_CACHE_TTL = config("ORS_CACHE_TTL", default=86400, cast=int)

LOGTAIL_TOKEN = config('LOGTAIL_TOKEN', default='')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'zaoapi.logging_config.JsonFormatter',
        },
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console_json': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
        'console_standard': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console_json'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console_json'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console_json'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console_json'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

if LOGTAIL_TOKEN:
    LOGGING['handlers']['logtail'] = {
        'class': 'logtail.LogtailHandler',
        'token': LOGTAIL_TOKEN,
        'formatter': 'json',
    }
    for logger_cfg in LOGGING['loggers'].values():
        logger_cfg['handlers'].append('logtail')
    LOGGING['root']['handlers'].append('logtail')

ROOT_URLCONF = 'zaoapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zaoapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default=None)
if not DATABASE_URL:
    DATABASE_URL = "postgresql://{user}:{password}@{host}:{port}/{name}".format(
        user=config('DATABASE_USER'),
        password=config('DATABASE_PASSWORD'),
        host=config('DATABASE_HOST'),
        port=config('DATABASE_PORT'),
        name=config('DATABASE_NAME'),
    )

url = urlparse(DATABASE_URL)
hostname = url.hostname
db_config = {
    'ENGINE': 'zaoapi.db_pool',
    'NAME': url.path[1:],
    'USER': url.username,
    'PASSWORD': url.password,
    'HOST': hostname,
    'PORT': url.port,
    'CONN_MAX_AGE': 600,
    'CONN_HEALTH_CHECKS': True,
    'OPTIONS': {},
}
if url.query:
    db_config['OPTIONS'] = dict(param.split('=', 1) for param in url.query.split('&'))
DATABASES = {'default': db_config}


# Database backups
DBBACKUP_CLEANUP = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

# M-Pesa Daraja API
MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY', default='')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET', default='')
MPESA_PASSKEY = config('MPESA_PASSKEY', default='')
MPESA_SHORTCODE = config('MPESA_SHORTCODE', default='')
MPESA_INITIATOR_NAME = config('MPESA_INITIATOR_NAME', default='testapi')
MPESA_INITIATOR_PASSWORD = config('MPESA_INITIATOR_PASSWORD', default='')
MPESA_PUBLIC_CERT_PATH = config('MPESA_PUBLIC_CERT_PATH', default=BASE_DIR / 'certs' / 'mpesa_public_cert.cer')
MPESA_ENVIRONMENT = config('MPESA_ENVIRONMENT', default='sandbox')
MPESA_B2C_RESULT_URL = config('MPESA_B2C_RESULT_URL', default='')
MPESA_B2C_TIMEOUT_URL = config('MPESA_B2C_TIMEOUT_URL', default='')
MPESA_DISBURSEMENT_BLACKOUT_START = config('MPESA_DISBURSEMENT_BLACKOUT_START', default='01:00')
MPESA_DISBURSEMENT_BLACKOUT_END = config('MPESA_DISBURSEMENT_BLACKOUT_END', default='04:00')
MPESA_CALLBACK_IP_WHITELIST = config('MPESA_CALLBACK_IP_WHITELIST', default='')
MPESA_CALLBACK_HMAC_SECRET = config('MPESA_CALLBACK_HMAC_SECRET', default='')

# Google OAuth
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')

# Google AI (Gemini)
GOOGLE_API_KEY = config('GOOGLE_API_KEY', default='')
GOOGLE_AI_MODEL = config('GOOGLE_AI_MODEL', default='gemini-2.5-flash')
GOOGLE_AI_TEMPERATURE = config('GOOGLE_AI_TEMPERATURE', default=0.7, cast=float)
GOOGLE_AI_MAX_TOKENS = config('GOOGLE_AI_MAX_TOKENS', default=4096, cast=int)
GOOGLE_AI_TIMEOUT = config('GOOGLE_AI_TIMEOUT', default=30, cast=int)

REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')

_redis_available = False
try:
    import redis as _redis
    _client = _redis.from_url(REDIS_URL, socket_connect_timeout=2)
    _client.ping()
    _client.close()
    _redis_available = True
except Exception:
    _redis_available = False

if _redis_available:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'TIMEOUT': 300,
        },
    }

# Celery configuration
CELERY_BROKER_URL = REDIS_URL if _redis_available else None
CELERY_RESULT_BACKEND = REDIS_URL if _redis_available else None
CELERY_TIMEZONE = 'Africa/Nairobi'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', default=False, cast=bool)
CELERY_TASK_EAGER_PROPAGATES = config('CELERY_TASK_EAGER_PROPAGATES', default=True, cast=bool)
CELERY_RESULT_EXPIRES = 3600
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'reconcile-stuck-disbursements': {
        'task': 'apps.disbursement.tasks.reconcile_stuck_transactions',
        'schedule': crontab(minute='*/15'),
    },
    'cleanup-expired-ussd-sessions': {
        'task': 'apps.notifications.tasks.cleanup_expired_ussd_sessions',
        'schedule': crontab(hour='2', minute='0'),
    },
    'cleanup-expired-otps': {
        'task': 'apps.auth_api.tasks.cleanup_expired_otps',
        'schedule': crontab(minute='*/30'),
    },
    'purge-deleted-records': {
        'task': 'apps.base.tasks.purge_deleted_records',
        'schedule': crontab(hour='1', minute='30'),
        'options': {'expires': 3600},
    },
    'analytics-daily-snapshots': {
        'task': 'apps.analytics.tasks.compute_daily_snapshots',
        'schedule': crontab(hour='0', minute='0'),
    },
    'analytics-weekly-snapshots': {
        'task': 'apps.analytics.tasks.compute_weekly_snapshots',
        'schedule': crontab(hour='1', minute='0', day_of_week='1'),
    },
    'analytics-monthly-snapshots': {
        'task': 'apps.analytics.tasks.compute_monthly_snapshots',
        'schedule': crontab(hour='2', minute='0', day_of_month='1'),
    },
    'analytics-materialized-monthly': {
        'task': 'apps.analytics.tasks.compute_materialized_monthly',
        'schedule': crontab(hour='3', minute='0', day_of_month='1'),
    },
    'analytics-warm-cache': {
        'task': 'apps.analytics.tasks.warm_analytics_cache',
        'schedule': crontab(minute='*/15'),
    },
    'analytics-refresh-leaderboards': {
        'task': 'apps.analytics.tasks.refresh_leaderboards',
        'schedule': crontab(minute='0'),
    },
    'database-backup': {
        'task': 'apps.base.tasks.backup_database',
        'schedule': crontab(minute=0, hour='*/6'),
        'options': {'expires': 3600},
    },
    'verify-backup-integrity': {
        'task': 'apps.base.tasks.verify_backup_integrity',
        'schedule': crontab(minute=30, hour='*/6'),
        'options': {'expires': 1800},
    },
}

NOTIFICATIONS_DRY_RUN = config('NOTIFICATIONS_DRY_RUN', default=True, cast=bool)
AFRICASTALKING_USSD_CODE = config('AFRICASTALKING_USSD_CODE', default='*384*11411#')
AFRICASTALKING_CALLBACK_IP_WHITELIST = config('AFRICASTALKING_CALLBACK_IP_WHITELIST', default='')

# Email — Django SMTP backend
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.sendgrid.net')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Zao <noreply@example.com>')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

STORAGES = {
    'default': {
        'BACKEND': DEFAULT_FILE_STORAGE,
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
    'dbbackup': {
        'BACKEND': config('DBBACKUP_STORAGE', default='cloudinary_storage.storage.CloudinaryMediaStorage'),
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'apps.base.throttles.GlobalUserRateThrottle',
        'apps.base.throttles.GlobalAnonRateThrottle',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/hour',
        'anon': '100/hour',
        'login': '10/min',
        'request_otp': '5/hour',
        'password_reset': '5/hour',
        'password_reset_verify': '30/min',
        'verify_otp': '5/min',
        'farmer_request_otp': '3/hour',
        'invite_request_otp': '3/hour',
        'invite_verify': '10/min',
        'superadmin': '100/min',
        'superadmin_sensitive': '3/hour',
        'legal_document': '20/min',
        'analytics_admin': '60/min',
        'analytics_staff': '30/min',
        'analytics_farmer': '10/min',
        'analytics_export': '5/hour',
        'payment_export': '10/hour',
        'global_search': '60/min',
        'route_ors': '30/min',
        'token_refresh': '30/min',
        'change_password': '5/min',
        'two_fa': '3/min',
        'chat': '30/hour',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Zao API',
    'DESCRIPTION': (
        'Zao is a comprehensive agricultural cooperative management platform '
        'that digitizes the entire farmer value chain, from collection '
        'and quality grading to payments, deductions, loans, and disbursements.\n\n'
        'The API enables cooperatives to manage farmers, track deliveries in '
        'real-time, compute payment cycles with automatic deductions, disburse '
        'payments via M-Pesa B2C (Daraja), bank transfers, or cash, and '
        'generate financial reports.\n\n'
        'All endpoints require JWT authentication unless noted otherwise. '
        'Include `Authorization: Bearer <token>` header.\n\n'
        '**Apps:**\n\n'
        '- **auth_api** — Authentication & JWT management: login, 2FA OTP (email), '
        'farmer OTP (SMS), token refresh, logout.\n'
        '- **cooperatives** — Cooperative entity CRUD with stats, enums, '
        'and current-cooperative lookup.\n'
        '- **users** — User account CRUD scoped to cooperative, self-profile endpoint.\n'
        '- **farmers** — Farmer profiles with full-text search, CSV import, '
        'nested cooperative membership (activate/deactivate).\n'
        '- **deliveries** — Milk delivery recording with offline sync, GPS map data, '
        'batch grouping, summary stats, SMS notifications.\n'
        '- **grading** — Milk quality grading with price tiers, manager overrides, '
        'image attachments, farmer disputes with resolution.\n'
        '- **inventory** — Read-only batch inventory with summary aggregation '
        'and low-stock threshold alerts.\n'
        '- **routes** — Collection route definitions with GPS stop assignment '
        'and farmer grouping.\n'
        '- **sales** — Buyer records and sales transactions with inventory '
        'availability checks.\n'
        '- **payment_engine** — Payment cycle lifecycle: draft, compute (Celery), '
        'preview, lock/unlock, hold/release payments, CSV export.\n'
        '- **deductions** — Loan repayment deductions and farm input credits, '
        'integrated with payment cycles.\n'
        '- **loans** — Loan lifecycle: create, approve, disburse, add/remove '
        'guarantors, mark completed or defaulted.\n'
        '- **disbursement** — Payment disbursement (M-Pesa B2C via Daraja, Bank, '
        'Cash): initiate, approve, send live, retry, export, confirm.\n'
        '- **notifications** — Notification log (SMS, email, in-app) and '
        "Africa's Talking USSD callback.\n"
        '- **statements** — Farmer payment PDF statements, payment history JSON, '
        'season/KRA/annual reports, audit log.'
    ),
    'VERSION': '1.0.0',
}

# Superadmin API
SUPERADMIN_ENABLED = config('SUPERADMIN_ENABLED', default=True, cast=bool)
SUPERADMIN_ALLOWED_IPS = config('SUPERADMIN_ALLOWED_IPS', default='', cast=lambda v: [i.strip() for i in v.split(',') if i.strip()])

# CORS - restrict in production
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="http://localhost:3000").split(",")
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:5173")

# HTTPS Security
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"

# Content Security Policy
# Allows Google Identity Services for OAuth sign-in and Google APIs
GOOGLE_SCRIPT_SRC = "https://accounts.google.com https://ajax.googleapis.com https://accounts.google.com/gsi/client"
CONTENT_SECURITY_POLICY = f"default-src 'self'; script-src 'self' 'unsafe-inline' {GOOGLE_SCRIPT_SRC}; style-src 'self' 'unsafe-inline'; img-src 'self' data: res.cloudinary.com; font-src 'self'; connect-src 'self' https://accounts.google.com https://oauth2.googleapis.com; frame-ancestors 'none'; form-action 'self'; base-uri 'self'"

# Permissions Policy
PERMISSIONS_POLICY = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), accelerometer=(), gyroscope=(), midi=(), sync-xhr=()"

# ── Sentry error tracking ──────────────────────────────────────────────
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration

SENTRY_DSN = config('SENTRY_DSN', default='')
ENVIRONMENT = config('ENVIRONMENT', default='development')


def _scrub_pii(event, hint):
    """Scrub Kenyan PII from error payloads before sending to Sentry.

    Covers:
    - Exception stack frame local variables
    - Sentry breadcrumbs (logged before the error)
    - Exception values and log message strings
    """
    import re

    phone_re = re.compile(r'(\+?254)\d{8,10}')
    id_re = re.compile(r'\b\d{8,10}\b')

    def _scrub_string(s):
        s = phone_re.sub('[PHONE_SCRUBBED]', s)
        s = id_re.sub('[ID_SCRUBBED]', s)
        return s

    def _scrub_val(val):
        if isinstance(val, str):
            return _scrub_string(val)
        return val

    # Scrub exception stack frames
    if 'exception' in event:
        for exc in event['exception'].get('values', []):
            for frame in exc.get('stacktrace', {}).get('frames', []):
                for key, val in frame.get('vars', {}).items():
                    frame['vars'][key] = _scrub_val(val)
            if 'value' in exc and isinstance(exc['value'], str):
                exc['value'] = _scrub_string(exc['value'])

    # Scrub breadcrumbs
    for bc in event.get('breadcrumbs', {}).get('values', []):
        if 'data' in bc and isinstance(bc['data'], dict):
            for key, val in bc['data'].items():
                bc['data'][key] = _scrub_val(val)
        if 'message' in bc and isinstance(bc['message'], str):
            bc['message'] = _scrub_string(bc['message'])

    # Scrub top-level message
    if 'message' in event and isinstance(event['message'], str):
        event['message'] = _scrub_string(event['message'])

    return event


if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration()],
        environment=ENVIRONMENT,
        traces_sample_rate=0.1,
        send_default_pii=False,
        enable_logs=True,
        before_send=_scrub_pii,
    )
