# Generated by Django 6.0.5 on 2026-05-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('payment_engine', '0002_farmerpayment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='farmer_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayments', to='payment_engine.farmerpayment'),
        ),
    ]
