# Generated by Django 6.0.5 on 2026-06-01 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0006_cooperative_minimum_payout_amount'),
        ('farmers', '0006_farmer_has_active_loan'),
        ('loans', '0002_alter_loanrepayment_farmer_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released')], default='ACTIVE', max_length=20)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='cooperatives.cooperative')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guaranteed_loans', to='farmers.farmer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loan')),
            ],
            options={
                'verbose_name': 'Loan Guarantor',
                'verbose_name_plural': 'Loan Guarantors',
                'unique_together': {('loan', 'guarantor')},
            },
        ),
    ]
