# Generated by Django 6.0.5 on 2026-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanguarantor'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='deleted_via_cascade_from',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='deleted_via_cascade_from',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
