# Generated by Django 6.0.5 on 2026-06-16 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_cooperative_prefix'),
        ('farmers', '0013_alter_farmer_date_joined_alter_farmer_is_active_and_more'),
        ('loans', '0004_loan_deleted_at_loan_deleted_via_cascade_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['cooperative', 'farmer', 'status'], name='idx_loan_coop_farmer_status'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(condition=models.Q(('status', 'ACTIVE')), fields=['cooperative', 'farmer'], name='idx_loan_active_by_coop_farmer'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['cooperative'], name='idx_loan_live_records'),
        ),
    ]
