# Generated by Django 6.0.5 on 2026-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
