# Generated by Django 6.0.5 on 2026-05-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmer_email_alter_farmer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='id_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mpesa_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
