# Generated by Django 6.0.5 on 2026-05-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_farmer_id_number_alter_farmer_mpesa_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='id_number',
            field=models.CharField(max_length=200),
        ),
    ]
