# Generated by Django 6.0.5 on 2026-05-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_farmer_latitude_farmer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='has_active_loan',
            field=models.BooleanField(default=False),
        ),
    ]
