# Generated by Django 6.0.5 on 2026-06-02 04:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0007_add_revenue_share_and_prorate_fields'),
        ('farmers', '0006_farmer_has_active_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='farmers_far_search__194ea7_gin'),
        ),
    ]
