# Generated by Django 6.0.5 on 2026-06-06 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0007_add_revenue_share_and_prorate_fields'),
        ('farmers', '0007_add_search_vector_and_gin_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='member_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mpesa_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('M-PESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FarmerCooperativeMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.CharField(editable=False, max_length=50)),
                ('payment_method', models.CharField(choices=[('M-PESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], default='M-PESA', max_length=20)),
                ('mpesa_number', models.CharField(blank=True, default='', max_length=30)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account', models.CharField(blank=True, default='', max_length=30)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_memberships', to='cooperatives.cooperative')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Farmer Cooperative Membership',
                'verbose_name_plural': 'Farmer Cooperative Memberships',
                'constraints': [models.UniqueConstraint(fields=('cooperative', 'member_number'), name='unique_member_per_coop')],
                'unique_together': {('farmer', 'cooperative')},
            },
        ),
    ]
