# Generated by Django 6.0.5 on 2026-06-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0009_backfill_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='member_number',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='mpesa_number',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='payment_method',
        ),
    ]
