# Generated by Django 6.0.5 on 2026-06-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0011_farmer_deleted_at_farmer_deleted_via_cascade_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmercooperativemembership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='farmercooperativemembership',
            name='deleted_via_cascade_from',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmercooperativemembership',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
