# Generated by Django 6.0.5 on 2026-06-16 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_cooperative_prefix'),
        ('farmers', '0012_add_soft_delete_to_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='farmercooperativemembership',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='farmercooperativemembership',
            name='payment_method',
            field=models.CharField(choices=[('M-PESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], db_index=True, default='M-PESA', max_length=20),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['cooperative', 'is_active', 'county'], name='idx_farmer_coop_active_county'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['cooperative', 'is_active', 'sub_county'], name='idx_farm_coop_act_subcounty'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['cooperative'], name='idx_farmer_live_records'),
        ),
        migrations.AddIndex(
            model_name='farmercooperativemembership',
            index=models.Index(fields=['cooperative', 'is_active', 'payment_method'], name='idx_mem_coop_active_method'),
        ),
        migrations.AddIndex(
            model_name='farmercooperativemembership',
            index=models.Index(condition=models.Q(('left_at__isnull', False)), fields=['cooperative'], name='idx_mem_left_coop'),
        ),
        migrations.AddIndex(
            model_name='farmercooperativemembership',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['cooperative'], name='idx_membership_live_records'),
        ),
    ]
