# Generated by Django 6.0.5 on 2026-06-13 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='e.g. privacy-policy, terms-of-service', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Markdown content')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('requires_acceptance', models.BooleanField(default=False, help_text='If True, users must accept the latest version before using the app')),
                ('published_at', models.DateTimeField(blank=True, help_text='Null means draft. Only documents with published_at <= now() are visible.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['-published_at', '-version'],
                'indexes': [models.Index(fields=['slug', 'is_active', 'published_at'], name='legal_legal_slug_3130b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(help_text='Snapshot of the document version at acceptance time')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='legal.legaldocument')),
            ],
            options={
                'verbose_name': 'Legal Acceptance',
                'verbose_name_plural': 'Legal Acceptances',
                'indexes': [models.Index(fields=['user', 'document'], name='legal_legal_user_id_798c30_idx')],
                'unique_together': {('user', 'document', 'version')},
            },
        ),
    ]
