# Generated by Django 6.0.5 on 2026-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='slug',
            field=models.SlugField(help_text='e.g. privacy-policy, terms-of-service', max_length=100),
        ),
    ]
