# Generated by Django 6.0.5 on 2026-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='inventory_updated',
            field=models.BooleanField(default=False),
        ),
    ]
