# Generated by Django 6.0.5 on 2026-06-15 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_deleted_at_and_more'),
        ('sales', '0003_buyer_deleted_at_buyer_deleted_via_cascade_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.inventory'),
        ),
        migrations.CreateModel(
            name='SaleInventoryLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Sale Inventory Line Item',
                'verbose_name_plural': 'Sale Inventory Line Items',
                'unique_together': {('sale', 'inventory')},
            },
        ),
    ]
