# Generated by Django 6.0.5 on 2026-06-16 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_cooperative_prefix'),
        ('inventory', '0003_inventory_deleted_at_and_more'),
        ('payment_engine', '0008_farmerpayment_idx_pay_coop_cycle_farmer_and_more'),
        ('sales', '0004_alter_sale_inventory_saleinventorylineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='grade_letter',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_type',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cooperative', 'status', 'sale_date'], name='idx_sale_coop_status_date'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cooperative', 'sale_date', 'buyer'], name='idx_sale_coop_date_buyer'),
        ),
    ]
