# Generated by Django 6.0.5 on 2026-07-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock_alter_inventory_options_and_more'),
        ('sales', '0005_alter_sale_grade_letter_alter_sale_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='inventory',
        ),
        migrations.AddField(
            model_name='sale',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.stock'),
        ),
    ]
